spring.application.name=JournalApp
spring.data.mongodb.uri = mongodb+srv://mehedipriam_db_user:vWm7qnY2orGo9i5j@cluster0.s56vqej.mongodb.net/journaldb?retryWrites=true&w=majority
spring.data.mongodb.database = journaldb
spring.data.mongodb.auto-index-creation=true
